<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataLoading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Data Loading or Data Parsing mean loading data and interpreting it as tables and different data types')

Data Loading or Data Parsing mean loading data and interpreting it as tables and different data types

### Reading and Writing Data in Text Format

In [2]:
ex1 = "https://raw.githubusercontent.com/wesm/pydata-book/3rd-edition/examples/ex1.csv"

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv(ex1)

In [4]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
ex2 = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex2.csv"

In [6]:
pd.read_csv(ex2 , header = None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [7]:
print("We can assign the default column names")

We can assign the default column names

In [8]:
pd.read_csv(ex2 , names = ['a' , 'b' , 'c' , 'd' , 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
print("Or Assign using names parameter")

Or Assign using names parameter

In [10]:
print("We can indicate we want to use message column as index")

We can indicate we want to use message column as index

In [11]:
names = ['a' , 'b' , 'c' , 'd' , 'message']
pd.read_csv(ex2 , names = names , index_col = 'message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [12]:
pd.read_csv(ex2 , names = names , index_col = 4)

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [13]:
print("Column to use as row label denoted either by column labels or column indices")

Column to use as row label denoted either by column labels or column indices

In [14]:
csv_mindex = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/csv_mindex.csv"

In [15]:
parsed = pd.read_csv(csv_mindex)

In [16]:
parsed

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [17]:
print("If we want heirarchical indexing from multiple columns , pass a list of column numbers or names")

If we want heirarchical indexing from multiple columns , pass a list of column numbers or names

In [18]:
parsed = pd.read_csv(csv_mindex , index_col = ['key1' , 'key2'])

In [19]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [20]:
ex3 = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex3.txt"

In [21]:
print("In Some cases a table might not have a fixed delimiter , using whitespace or some other pattern to separate fields")

In Some cases a table might not have a fixed delimiter , using whitespace or some other pattern to separate fields

In [22]:
!cat ex3.txt

cat: ex3.txt: No such file or directory

In [23]:
result = pd.read_csv(ex3 , sep = '\s+')

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_76072/3294471038.py:1: SyntaxWarning: invalid escape sequence '\s'
  result = pd.read_csv(ex3 , sep = '\s+')

In [24]:
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [25]:
print("Because there was one less column than the row , pandas infers that the first column should be index column")

Because there was one less column than the row , pandas infers that the first column should be index column

In [26]:
ex4 = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex4.csv"

In [27]:
pd.read_csv(ex4)

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [28]:
pd.read_csv(ex4 , skiprows = [0 , 2 , 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [29]:
print("We can skip rows with skip rows argument")

We can skip rows with skip rows argument

In [30]:
print('Handling Missing values is also important')

Handling Missing values is also important

In [31]:
print("Missing data is usually not present or marked by some sentinal value , pandas commonly use Na and Null")

Missing data is usually not present or marked by some sentinal value , pandas commonly use Na and Null

In [32]:
ex5 = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex5.csv"

In [33]:
result = pd.read_csv(ex5)

In [34]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [35]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [36]:
result = pd.read_csv(ex5 , na_values = ["one"])
result

  something  a   b     c   d message
0       NaN  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [37]:
print("""Pandas automatically recognizes standard missing markers like 'NA', 'NaN', 'null', and empty cells
na_values allows you to define additional custom markers(such as -999, 'NA', 'Missing', or '?')""")

Pandas automatically recognizes standard missing markers like 'NA', 'NaN', 'null', and empty cells
na_values allows you to define additional custom markers(such as -999, 'NA', 'Missing', or '?')

In [38]:
pd.isna(result)

   something      a      b      c      d  message
0       True  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [39]:
print("We can disable the default NA value respresentations")

We can disable the default NA value respresentations

In [40]:
result2 = pd.read_csv(ex5 , keep_default_na = False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [41]:
pd.isna(result2)

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [42]:
result3 = pd.read_csv(ex5 , na_values = ["NA"] , keep_default_na = False)
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [43]:
pd.isna(result3)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [44]:
print("We can specify different NA sentinels for each column in a dict")

We can specify different NA sentinels for each column in a dict

In [45]:
sentinals = {
    'message' : ['foo' , 'NA'] ,
    'something' : ['two']
}

In [46]:
pd.read_csv(ex5 , na_values = sentinals , keep_default_na = False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

In [47]:
pd.read_csv(ex5 , engine = 'pyarrow')

  something  a   b     c   d message
0       one  1   2   3.0   4    None
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [48]:
pd.read_csv(ex5 , nrows = 2)

  something  a  b    c  d message
0       one  1  2  3.0  4     NaN
1       two  5  6  NaN  8   world

In [49]:
pd.read_csv(ex5 , verbose = True)

Tokenization took: 0.01 ms
Type conversion took: 0.28 ms
Parser memory cleanup took: 0.01 ms

/tmp/ipykernel_76072/2566253726.py:1: FutureWarning: The 'verbose' keyword in pd.read_csv is deprecated and will be removed in a future version.
  pd.read_csv(ex5 , verbose = True)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [50]:
def clean(x):
  return x.strip().capitalize()
def remove_dec(x):
    if x == '' or pd.isna(x):
        return np.nan
    return int(float(x))

pd.read_csv(ex5 , converters = {'message' : clean , 'c' : remove_dec})

  something  a   b     c   d message
0       one  1   2   3.0   4      Na
1       two  5   6   NaN   8   World
2     three  9  10  11.0  12     Foo

In [51]:
pd.read_csv(ex5 , skipfooter = 2)

/tmp/ipykernel_76072/1381069607.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  pd.read_csv(ex5 , skipfooter = 2)

  something  a  b  c  d  message
0       one  1  2  3  4      NaN

In [52]:
pd.read_csv(ex5 , encoding = 'utf-8')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [53]:
pd.read_csv(ex5 , thousands = ',')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [54]:
print("Learnt Till Now : Path , sep or delimiter , header , index_col , names , skiprows , keep_default_na , na_values , comment , converters , nrows , skipfooter , verbose , encoding , engine , thousands , decimals")

Learnt Till Now : Path , sep or delimiter , header , index_col , names , skiprows , keep_default_na , na_values , comment , converters , nrows , skipfooter , verbose , encoding , engine , thousands , decimals

### Reading Test Files in Pieces

In [55]:
ex6 = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex6.csv"

In [56]:
pd.read_csv(ex6)

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [57]:
pd.read_csv(ex6 , nrows = 5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [58]:
chunker = pd.read_csv(ex6 , chunksize = 1000)

In [59]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [60]:
chunker = pd.read_csv(ex6 , chunksize = 2500)
for piece in chunker :
  print(piece)

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
2495  1.345822  2.363195 -1.405568  2.599800   8
2496  0.173217 -0.116329  0.373466  0.381805   V
2497 -0.289274  1.439352 -0.799853 -1.208543   E
2498  1.094008  0.049683 -1.445820  0.540209   3
2499  0.290745  0.590175  0.895260 -0.025518   8

[2500 rows x 5 columns]
           one       two     three      four key
2500 -0.264040 -1.204051  0.504199  0.602873   I
2501  2.027584 -0.097576 -0.445689  1.965018   L
2502  1.342573  1.231400  1.723257  1.332216   R
2503  1.536042  1.585264  0.904740  0.972697   T
2504 -0.494593  0.008418  1.512647 -0.114531   P
...        ...       ...       ...       ...  ..
4995  2.311896 -0.417070 -1.409599 -0.515821   X
4996 -0.479893 -0.650419  0.745152 -0.646038   M
4997  0.523331  0.787112  0.486066  1.093156   5
4998 -0.362559  0.598894 -1.843201  0.887292   T
4999 -0.096376 -1.012999 -0.657431 -0.573315   U

[2500 rows x 5 columns]
           one       two     three      four key
5000  0.467976 -0.038649 -0.295344 -1.824726   1
5001 -0.358893  1.404453  0.704965 -0.200638   Z
5002 -0.501840  0.659254 -0.421691 -0.057688   3
5003  0.204886  1.074134  1.388361 -0.982404   H
5004  0.354628 -0.133116  0.283763 -0.837063   B
...        ...       ...       ...       ...  ..
7495  1.345822  2.363195 -1.405568  2.599800   V
7496  0.173217 -0.116329  0.373466  0.381805   Y
7497 -0.289274  1.439352 -0.799853 -1.208543   F
7498  1.094008  0.049683 -1.445820  0.540209   H
7499  0.290745  0.590175  0.895260 -0.025518   I

[2500 rows x 5 columns]
           one       two     three      four key
7500 -0.264040 -1.204051  0.504199  0.602873   Y
7501  2.027584 -0.097576 -0.445689  1.965018   M
7502  1.342573  1.231400  1.723257  1.332216   0
7503  1.536042  1.585264  0.904740  0.972697   N
7504 -0.494593  0.008418  1.512647 -0.114531   C
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[2500 rows x 5 columns]

In [61]:
print(chunker)

<pandas.io.parsers.readers.TextFileReader object at 0x7fbab6ef1130>

In [62]:
chunker = pd.read_csv(ex6 , chunksize = 2500)
tot = pd.Series([] , dtype = 'int64')
for piece in chunker :
  tot = tot.add(piece['key'].value_counts() , fill_value = 0)

tot = tot.sort_values(ascending = False)

In [63]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [64]:
print("Pandas returns a TextFileReader object Once iterated through it the internal file pointer reaches the end of the file and the iterator becomes exhausted")

Pandas returns a TextFileReader object Once iterated through it the internal file pointer reaches the end of the file and the iterator becomes exhausted

In [65]:
reader = pd.read_csv(ex6 , iterator = True)
first_batch = reader.get_chunk(5)
second_batch = reader.get_chunk(100)

In [66]:
print(first_batch)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [67]:
print(second_batch)

          one       two     three      four key
5    1.817480  0.742273  0.419395 -2.251035   Q
6   -0.776764  0.935518 -0.332872 -1.875641   U
7   -0.913135  1.530624 -0.572657  0.477252   K
8    0.358480 -0.497572 -0.367016  0.507702   S
9   -1.740877 -1.160417 -1.637830  2.172201   G
..        ...       ...       ...       ...  ..
100 -0.602748 -0.182504 -0.768164  1.260686   X
101 -0.039105 -0.069510 -1.358052 -0.292859   0
102 -0.345101 -0.179477 -0.904658 -0.071287   T
103 -0.759495  0.225916  2.235872 -0.004490   X
104 -1.686771  0.742276  0.485876  1.798507   Q

[100 rows x 5 columns]

In [68]:
print("While setting chunksize automatically splits your data into fixed equal sizes for a loop, get_chunk() allows you to manually pull a specific number of rows on demand from the stream")

While setting chunksize automatically splits your data into fixed equal sizes for a loop, get_chunk() allows you to manually pull a specific number of rows on demand from the stream

### Writing Data to Text Format

In [69]:
data = pd.read_csv(ex5)
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [70]:
data.to_csv("out.csv")

In [71]:
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [72]:
print("Using DataFrame's to csv method , we can write the data out to comma separated file")

Using DataFrame's to csv method , we can write the data out to comma separated file

In [73]:
import sys
data.to_csv(sys.stdout , sep = '|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [74]:
print("Other delimiters can be used with sys and specifing the delim")

Other delimiters can be used with sys and specifing the delim

In [75]:
print("Missing values appears as empty strings in the output , We might want to denote them by some other sentinal value")

Missing values appears as empty strings in the output , We might want to denote them by some other sentinal value

In [76]:
data.to_csv(sys.stdout , na_rep = 'Nothing')

,something,a,b,c,d,message
0,one,1,2,3.0,4,Nothing
1,two,5,6,Nothing,8,world
2,three,9,10,11.0,12,foo

In [77]:
data.to_csv(sys.stdout , index = False , header = False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [78]:
print("With No Options specified both row and column labels are written but both can be disabled")

With No Options specified both row and column labels are written but both can be disabled

In [79]:
data.to_csv(sys.stdout , index = False , columns = ['a' , 'b' , 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [80]:
print("Only a subset of columns can be outputed by columns arg")

Only a subset of columns can be outputed by columns arg

### Working with Other Delimited Formats

In [81]:
print("read_csv is high level foundation and crashes if it encounters unexpected glitches like broken quotes, mismatched column counts or non-standard characters")

read_csv is high level foundation and crashes if it encounters unexpected glitches like broken quotes, mismatched column counts or non-standard characters

In [82]:
print("While csv.reader is a low level convenience tool")

While csv.reader is a low level convenience tool

In [83]:
print("read_csv outputs a fully structured Dataframe while reader outputs a raw stream of string")

read_csv outputs a fully structured Dataframe while reader outputs a raw stream of string

In [84]:
ex7 = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex7.csv"

In [85]:
import csv
f = open("/content/ex7.csv")
reader = csv.reader(f)

In [86]:
for line in reader :
  print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [87]:
f.close()

In [88]:
print("The necessary wrangling to put the data in the form that we need")

The necessary wrangling to put the data in the form that we need

In [89]:
with open("/content/ex7.csv") as f :
  lines = list(csv.reader(f))

In [90]:
print("We can split the lines into the header line and data lines")

We can split the lines into the header line and data lines

In [91]:
header , values = lines[0] , lines[1:]

In [92]:
header

['a', 'b', 'c']

In [93]:
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [94]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [95]:
print("We can use Direct keyword Argument or Use custom class")

We can use Direct keyword Argument or Use custom class

In [96]:
f = open('/content/ex7.csv')

In [97]:
reader = csv.reader(f , delimiter = "|")

In [98]:
reader

In [99]:
for i in reader :
  print(i)

['a,"b","c"']
['1,"2","3"']
['1,"2","3"']

In [100]:
class my_dialect(csv.Dialect):
  lineterminator = '\n'
  delimiter = ';'
  quotechar = '"'
  quoting = csv.QUOTE_MINIMAL

reader = csv.reader(f , dialect = my_dialect)

In [101]:
f = open("/content/cleaning.txt")

In [102]:
reader = csv.reader(f)

In [103]:
for i in reader :
  print(i)

["'ID'~'Name'~'Description'~'Status'|"]
["'101'~'Alice'~'Likes commas", " like this'~'ACTIVE'|"]
["'102'~'Bob'~'Has a ''single quote'' inside'~'PENDING'|"]
["'103'~'Charlie'~'Escaped \\~ tilde character'~'NONE'|"]
["'104'~'Diana'~'No quotes needed'~'ACTIVE'|"]

In [104]:
class delim(csv.Dialect):
  lineterminator = '||n'
  delimiter = '~'
  quotechar = "'"
  escapechar = "\\"
  skipinitialspace = True
  quoting = csv.QUOTE_MINIMAL

In [105]:
f.seek(0)

0

In [106]:
reader = csv.reader(f , dialect = delim)

In [107]:
for i in reader :
  print(i)

['ID', 'Name', 'Description', 'Status|']
['101', 'Alice', 'Likes commas, like this', 'ACTIVE|']
['102', 'Bob', "Has a 'single quote'' inside'", 'PENDING|']
['103', 'Charlie', 'Escaped ~ tilde character', 'NONE|']
['104', 'Diana', 'No quotes needed', 'ACTIVE|']

In [108]:
print("For files with more complicated or fixed multicharacter delimiters we will not be able to use the csv module ")

For files with more complicated or fixed multicharacter delimiters we will not be able to use the csv module

In [109]:
print("Will have to do the line splitting and other cleanup using the string’s split method or the regular expression method re.split.")

Will have to do the line splitting and other cleanup using the string’s split method or the regular expression method re.split.

In [110]:
print('To write delimited files manually we can use csv.writer')

To write delimited files manually we can use csv.writer

In [111]:
print("csv.writer is the exact inverse of csv.reader , Instead of parsing a single string into a list, it takes Python sequences and formats them into delimited string rows according to your dialect rules")

csv.writer is the exact inverse of csv.reader , Instead of parsing a single string into a list, it takes Python sequences and formats them into delimited string rows according to your dialect rules

### JSON Data

In [112]:
print("JSON Stands for Java Script Object Notation")

JSON Stands for Java Script Object Notation

In [113]:
print("Standard formats for sending data by HTTP request btw web browsers and other applications")

Standard formats for sending data by HTTP request btw web browsers and other applications

JSON is very nearly valid Python code with the exception of its null value null and
some other nuances (such as disallowing trailing commas at the end of lists). The
basic types are objects (dictionaries), arrays (lists), strings, numbers, Booleans, and
nulls. All of the keys in an object must be strings. There are several Python libraries
for reading and writing JSON data.

In [114]:
obj = """
{"name": "Wes",
"pet": null,
"cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
"siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
{"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

In [115]:
import json

In [116]:
result = json.loads(obj)

In [117]:
result

{'name': 'Wes',
 'pet': None,
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [118]:
asjson = json.dumps(result)

In [119]:
asjson

'{"name": "Wes", "pet": null, "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [120]:
print("Json.dumps converts a Python object back to JSON")

Json.dumps converts a Python object back to JSON

In [121]:
print("pandas.read_json can automatically convert JSON datasets into Series and Dataframe")

pandas.read_json can automatically convert JSON datasets into Series and Dataframe

In [122]:
json_ex = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/example.json"

In [123]:
data = pd.read_json(json_ex)

In [124]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [125]:
print("We can export data from Pandas to JSON using to_json methods on Series or DataFrame")

We can export data from Pandas to JSON using to_json methods on Series or DataFrame

In [126]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [127]:
data.to_json(sys.stdout , orient = 'records')

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

### XML and HTML : Web Scraping

#### HTML

In [128]:
print("Python has many libraries for reading and writing data in HTML and XML format")

Python has many libraries for reading and writing data in HTML and XML format

In [129]:
print("Examples lxml , Beautiful Soup and html5lib")

Examples lxml , Beautiful Soup and html5lib

In [130]:
print("While lxml is comparatively much faster but other libraries can better handle malformed HTML or XML files")

While lxml is comparatively much faster but other libraries can better handle malformed HTML or XML files

In [131]:
print("pandas has a built in function , pandas.read_html which uses all of those libraries to parse tables out of HTML files as DataFrame objects")

pandas has a built in function , pandas.read_html which uses all of those libraries to parse tables out of HTML files as DataFrame objects

In [132]:
html_ex = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/fdic_failed_bank_list.html"

In [133]:
tables = pd.read_html(html_ex)

In [134]:
len(tables)

1

In [135]:
len(tables[0])

547

In [136]:
failures = tables[0]

In [137]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [138]:
print("Computing the number of bank failures by year")

Computing the number of bank failures by year

In [139]:
close_timestamps = pd.to_datetime(failures["Closing Date"])

In [140]:
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [141]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

#### XML

In [142]:
print("XML Supports heirarcial , nested data with metadata similar to HTML but more general")

XML Supports heirarcial , nested data with metadata similar to HTML but more general

In [143]:
from lxml import objectify

In [144]:
path = "/content/Performance_MNR.xml"

In [145]:
with open(path) as f :
  parsed = objectify.parse(f)
root = parsed.getroot()

In [146]:
print("lxml.objectify parse the file and get the reference to the root node of the XML file with getroot")

lxml.objectify parse the file and get the reference to the root node of the XML file with getroot

In [147]:
print("root.INDICATOR returns a generator yeilding each <INDICATOR> XML element")

root.INDICATOR returns a generator yeilding each <INDICATOR> XML element

In [148]:
print("For each record we populate the dict of tag names to data values")

For each record we populate the dict of tag names to data values

In [149]:
data = []
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ","DESIRED_CHANGE", "DECIMAL_PLACES"]

In [150]:
for elt in root.INDICATOR :
  el_data = {}
  for child in elt.getchildren():
    if child.tag in skip_fields :
      continue
    el_data[child.tag] = child.pyval
  data.append(el_data)

In [151]:
print("Lastly convert this list of Dict to Dataframe")

Lastly convert this list of Dict to Dataframe

In [152]:
perf = pd.DataFrame(data)

In [153]:
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [154]:
print("Pandas pd.read_xml function turns this process into a one line expression")

Pandas pd.read_xml function turns this process into a one line expression

In [155]:
perf_2 = pd.read_xml(path)

In [156]:
perf_2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

### Binary Data Format

In [157]:
print("One Way to store data in binary format is to use Python's built in pickle module")

One Way to store data in binary format is to use Python's built in pickle module

In [158]:
frame = pd.read_csv(ex1)

In [159]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [160]:
frame.to_pickle("frame_pickle")

In [161]:
pd.read_pickle("/content/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### Microsolf Excell Files

In [162]:
print("Reading tabular data stored in Excel files can be read using pd.read_excel")

Reading tabular data stored in Excel files can be read using pd.read_excel

In [163]:
print("Internally they use xlrd and openpyxl")

Internally they use xlrd and openpyxl

In [164]:
frame = pd.read_excel('/content/ex1.xlsx' , sheet_name = "Sheet1")
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [165]:
frame.to_excel("frame_excel.xlsx")

### HDF5 Format

HDF5 is a respected file format intended for storing large quantities of scientific array
data. It is available as a C library, and it has interfaces available in many other lan‐
guages, including Java, Julia, MATLAB, and Python. The “HDF” in HDF5 stands for
hierarchical data format. Each HDF5 file can store multiple datasets and supporting
metadata. Compared with simpler formats, HDF5 supports on-the-fly compression
with a variety of compression modes, enabling data with repeated patterns to be
stored more efficiently. HDF5 can be a good choice for working with datasets that
don’t fit into memory, as you can efficiently read and write small sections of much
larger arrays.

In [166]:
frame = pd.DataFrame({
    "a" : np.random.standard_normal(100)
})

In [167]:
frame

           a
0   1.349721
1   1.003724
2   1.113683
3   0.671253
4   0.584035
..       ...
95 -1.793712
96 -0.659136
97  1.384137
98 -0.252602
99  1.024383

[100 rows x 1 columns]

In [168]:
store = pd.HDFStore("mydata.h5")

In [169]:
store['obj1'] = frame

In [170]:
store['obj1_col'] = frame['a']

In [171]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [172]:
store["obj1"]

           a
0   1.349721
1   1.003724
2   1.113683
3   0.671253
4   0.584035
..       ...
95 -1.793712
96 -0.659136
97  1.384137
98 -0.252602
99  1.024383

[100 rows x 1 columns]

In [173]:
store["obj1_col"]

0     1.349721
1     1.003724
2     1.113683
3     0.671253
4     0.584035
        ...
95   -1.793712
96   -0.659136
97    1.384137
98   -0.252602
99    1.024383
Name: a, Length: 100, dtype: float64

In [174]:
print("Here store['obj1'] stores the entire DataFrame and store['obj1_col'] stores only a single column which is a Pandas Series")

Here store['obj1'] stores the entire DataFrame and store['obj1_col'] stores only a single column which is a Pandas Series

In [175]:
store.put("obj2" , frame , format = "table")

In [176]:
store["obj2"]

           a
0   1.349721
1   1.003724
2   1.113683
3   0.671253
4   0.584035
..       ...
95 -1.793712
96 -0.659136
97  1.384137
98 -0.252602
99  1.024383

[100 rows x 1 columns]

In [177]:
print("Using store['obj1'] = frame forces pandas to use default settings whereas store.put() unlocks advanced features like querying and appending")

Using store['obj1'] = frame forces pandas to use default settings whereas store.put() unlocks advanced features like querying and appending

In [178]:
store.select("obj2" , where = ['index >= 10 and index <= 15'])

           a
10  0.264116
11 -1.691522
12 -0.894006
13 -0.079058
14 -0.544770
15  0.528888

In [179]:
print("pandas.read_hdf function does all these")

pandas.read_hdf function does all these

In [180]:
frame.to_hdf('/content/mydata.h5' , 'obj3' , format = 'table')

/tmp/ipykernel_76072/4101139915.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  frame.to_hdf('/content/mydata.h5' , 'obj3' , format = 'table')

In [181]:
pd.read_hdf("/content/mydata.h5" , 'obj3')

           a
0   1.349721
1   1.003724
2   1.113683
3   0.671253
4   0.584035
..       ...
95 -1.793712
96 -0.659136
97  1.384137
98 -0.252602
99  1.024383

[100 rows x 1 columns]

In [182]:
pd.read_hdf("/content/mydata.h5" , 'obj3' , where = ['index < 5'])

          a
0  1.349721
1  1.003724
2  1.113683
3  0.671253
4  0.584035

In [183]:
print("Deleting a File can be done by remove")

Deleting a File can be done by remove

In [184]:
import os

In [185]:
os.remove("/content/mydata.h5")

### Web APIs

In [186]:
print("Many websites have public APIs providing data feeds via JSON or some other format")

Many websites have public APIs providing data feeds via JSON or some other format

In [187]:
print("There are a number of ways to access these APIs from Python , one method is the requests package")

There are a number of ways to access these APIs from Python , one method is the requests package

In [188]:
import requests

In [189]:
print("Last 30 GitHub issues for Pandas on GitHub")

Last 30 GitHub issues for Pandas on GitHub

In [190]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

In [191]:
resp = requests.get(url)

In [192]:
resp.raise_for_status()

In [193]:
resp

In [194]:
data = resp.json()

In [195]:
print("The response object’s json method will return a Python object containing the parsed JSON data as a dictionary or list")

The response object’s json method will return a Python object containing the parsed JSON data as a dictionary or list

In [196]:
issues = pd.DataFrame(data , columns = ['number' , 'title' , 'labels' , 'state'])

In [197]:
issues

,number,title,labels,state
0,67857,DOC: use Sphinx cross-references instead of ha...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
1,67826,"BUG: zoneinfo ""big bang"" transition wraps to 1...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
2,67824,TST: remove redundant length-zero string test ...,[],open
3,67786,BUG: IntervalDtype.__from_arrow__ ignores stru...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
4,67758,BUG: read_csv raised IndexError from the mixed...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
5,67756,API: `.value_counts(normalize=False)` should r...,[],open
6,67755,"BUG: DataFrame.plot.bar raises ""Must supply fr...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
7,67754,BUG: IntervalDtype.__from_arrow__ ignores the ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
8,67753,BUG: IntervalArray.__arrow_array__ rejects Ext...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,67751,DOC: Opening a Pull Request Instructions Incor...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
10,67750,ENH: Expose Resampler classes in pandas.api.ty...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
11,67728,ENH: Add DataFrame.headtail() to show first an...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
12,67727,BUG: barcharts grouped in subplots behave inco...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
13,67726,BUG: IndexError with certain subplot order in ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
14,67725,BUG: read_csv low_memory mixed-dtype warning n...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
15,67723,BUG: assert_series_equal wrong with check_cate...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
16,67716,[fix: #66346] deprecate get nth item with [] b...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
17,67628,BUG: IntervalDtype.__from_arrow__ with an Exte...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,67626,BUG: fix IndexError when usecols selects a col...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
19,67625,ENH: Add pyarrow/auto engine options to DataFr...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
20,67623,BUG: preserve arrow extension arrays,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
21,67553,BUG: str.get_dummies gave a column to entries ...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
22,67470,ENH: include cell location in ExcelWriter warn...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
23,67463,BUG: Handle empty schemas in ADBC has_table,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
24,67462,BUG: Make RangeIndex._data read-only to preven...,[],open
25,67446,BUG/PERF: Series.combine passes Series on dupl...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,67406,BUG: qcut does not validate a non-positive int...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
27,67381,TST: cover negative nanosecond merge_asof tole...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
28,67376,BUG: to_string ignored min_rows=1 and showed m...,"[{'id': 11527065930, 'node_id': 'LA_kwDOAA0YD8...",open
29,67375,BUG: read_csv with usecols raises IndexError i...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open

### DataBases

In [198]:
print('Many times data can be stored in SQL-based relational Databases (SQL Server , PostgreSQL , MySQl)')

Many times data can be stored in SQL-based relational Databases (SQL Server , PostgreSQL , MySQl)

In [199]:
import sqlite3

In [200]:
print("Create table and insert data using sqlite3")

Create table and insert data using sqlite3

In [201]:
con = sqlite3.connect("mydata.sqlite")

In [202]:
query = """
CREATE TABLE IF NOT EXISTS test
(a VARCHAR(20), b VARCHAR(20), c REAL, d INTEGER);
"""

In [203]:
con.execute(query)

In [204]:
print("Insert Few rows of data")

Insert Few rows of data

In [205]:
data = [
    ("Atlanta", "Georgia", 1.25, 6),
    ("Tallahassee", "Florida", 2.6, 3),
    ("Sacramento", "California", 1.7, 5)
]

In [206]:
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [207]:
con.executemany(stmt, data)

In [208]:
con.commit()

In [209]:
con.close()

In [210]:
print("Now connect to the same SQLite database with SQLAlchemy and read data from the table created before")

Now connect to the same SQLite database with SQLAlchemy and read data from the table created before

In [211]:
import sqlalchemy as sqla

In [212]:
db = sqla.create_engine("sqlite:///mydata.sqlite")

In [213]:
pd.read_sql("SELECT * FROM test" , db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5
3      Atlanta     Georgia  1.25  6
4  Tallahassee     Florida  2.60  3
5   Sacramento  California  1.70  5