<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Date - 18 th Aug 2026

In [2]:
a = 5
print(id(a))

11278056

In [3]:
a += 1
print(id(a))

11278088

In [4]:
print("""Here Id changes because in python int is immutable
while doing += it creates a copy of the variable appends
and then re initiate the variable with the value
while in cpp int (untill specified const) overwrites the bytes stored at memory address directly """)

Here Id changes because in python int is immutable
while doing += it creates a copy of the variable appends
and then re initiate the variable with the value
while in cpp int (untill specified const) overwrites the bytes stored at memory address directly

### Arithimatic and Data Alignment

In [5]:
import pandas as pd
import numpy as np

In [6]:
s1 = pd.Series([1 , 2 , 3 , 4 , 5] , index = list("abcde"))
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
s2 = pd.Series([4 , 5 , 6] , index = list('dfg') )
s2

d    4
f    5
g    6
dtype: int64

In [8]:
s1 + s2

a    NaN
b    NaN
c    NaN
d    8.0
e    NaN
f    NaN
g    NaN
dtype: float64

In [9]:
print("The internal data alignment introduces missing values in the label locations that don’t overlap")

The internal data alignment introduces missing values in the label locations that don’t overlap

In [10]:
df1 = pd.DataFrame(columns = ['a'] , index = [1 , 2])
df1

     a
1  NaN
2  NaN

In [11]:
df2 = pd.DataFrame(columns = ['b'] , index = [1 , 2])
df2

     b
1  NaN
2  NaN

In [12]:
df1 + df2

     a    b
1  NaN  NaN
2  NaN  NaN

In [13]:
df1 = pd.DataFrame(np.arange(25).reshape((5 ,5 )) , index = list("abcde") , columns = list("abcde"))
df1

    a   b   c   d   e
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24

In [14]:
df2 = pd.DataFrame(np.arange(25).reshape((5 , 5)) , index = list("abcef") , columns = list("abcdf"))
df2

    a   b   c   d   f
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
e  15  16  17  18  19
f  20  21  22  23  24

In [15]:
df1+df2

      a     b     c     d   e   f
a   0.0   2.0   4.0   6.0 NaN NaN
b  10.0  12.0  14.0  16.0 NaN NaN
c  20.0  22.0  24.0  26.0 NaN NaN
d   NaN   NaN   NaN   NaN NaN NaN
e  35.0  37.0  39.0  41.0 NaN NaN
f   NaN   NaN   NaN   NaN NaN NaN

In [16]:
print("All Non overlapping columns and rows will produce Nan Values")

All Non overlapping columns and rows will produce Nan Values

#### Arithmetic Methods to fill values

In [17]:
df1 = pd.DataFrame(np.arange(12).reshape((3 , 4)) , columns = list('abcd'))
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [18]:
df2 = pd.DataFrame(np.arange(20).reshape((4 , 5)) , columns = list("abcde"))
df2

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [19]:
df2.loc[1 , 'b'] = np.nan

In [20]:
df2

    a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [21]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [22]:
df1.add(df2 , fill_value = 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [23]:
1/df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [24]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [25]:
df1.div(2)

     a    b    c    d
0  0.0  0.5  1.0  1.5
1  2.0  2.5  3.0  3.5
2  4.0  4.5  5.0  5.5

In [26]:
print("When reindexing a Series or DataFrame you can also specify a different fill")

When reindexing a Series or DataFrame you can also specify a different fill

In [27]:
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [28]:
df2

    a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [29]:
df1.reindex(columns = df2.columns , fill_value = 0)

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [30]:
df1.mul(df2 , fill_value = 2)

      a     b      c      d     e
0   0.0   1.0    4.0    9.0   8.0
1  20.0  10.0   42.0   56.0  18.0
2  80.0  99.0  120.0  143.0  28.0
3  30.0  32.0   34.0   36.0  38.0

In [31]:
df1.mul(2)

    a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22

In [32]:
df1.rmul(2)

    a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22

In [33]:
df1.pow(2)

    a   b    c    d
0   0   1    4    9
1  16  25   36   49
2  64  81  100  121

In [34]:
df1.rpow(2)

     a    b     c     d
0    1    2     4     8
1   16   32    64   128
2  256  512  1024  2048

In [35]:
print("pow is (element) to the power (arg) and rpow is (arg) to the power (element)")

pow is (element) to the power (arg) and rpow is (arg) to the power (element)

In [36]:
print("r interchanges the position of arg with element ")

r interchanges the position of arg with element

#### Operations between DataFrame and Series

In [37]:
print("Consider the difference between 1D array and 2D array")

Consider the difference between 1D array and 2D array

In [38]:
arr = np.arange(24).reshape((4 , 6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
arr[0]

array([0, 1, 2, 3, 4, 5])

In [40]:
arr - arr[0]

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [41]:
frame = pd.DataFrame(np.arange(12).reshape((3 , 4)) , columns = list('ABCD') , index = list('abc'))
frame

   A  B   C   D
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [42]:
series = frame.iloc[0]

In [43]:
series

A    0
B    1
C    2
D    3
Name: a, dtype: int64

In [44]:
frame - series

   A  B  C  D
a  0  0  0  0
b  4  4  4  4
c  8  8  8  8

In [45]:
print("Arithmetic between DataFrame and Series matches the index of the Series on the columns of the DataFrame, broadcasting down the rows")

Arithmetic between DataFrame and Series matches the index of the Series on the columns of the DataFrame, broadcasting down the rows

In [46]:
series2 = pd.Series(np.arange(4) , index = list('ABDE'))
series2

A    0
B    1
D    2
E    3
dtype: int64

In [47]:
frame + series2

     A     B   C     D   E
a  0.0   2.0 NaN   5.0 NaN
b  4.0   6.0 NaN   9.0 NaN
c  8.0  10.0 NaN  13.0 NaN

In [48]:
print("If an index value is not found in either the DataFrame’s columns or the Series’s index, the objects will be reindexed to form the union")

If an index value is not found in either the DataFrame’s columns or the Series’s index, the objects will be reindexed to form the union

In [49]:
series2 = pd.Series(np.arange(4) , index = list('abce'))

In [50]:
series2

a    0
b    1
c    2
e    3
dtype: int64

In [51]:
frame + series2

    A   B   C   D   a   b   c   e
a NaN NaN NaN NaN NaN NaN NaN NaN
b NaN NaN NaN NaN NaN NaN NaN NaN
c NaN NaN NaN NaN NaN NaN NaN NaN

In [52]:
print("Normally Adding both will give an NaN matrix as they will try to add column wise")

Normally Adding both will give an NaN matrix as they will try to add column wise

In [53]:
frame.add(series2 , axis = "index")

      A     B     C     D
a   0.0   1.0   2.0   3.0
b   5.0   6.0   7.0   8.0
c  10.0  11.0  12.0  13.0
e   NaN   NaN   NaN   NaN

### Function Application and Mapping

In [54]:
print("NumPy ufuncs also work with pandas")

NumPy ufuncs also work with pandas

In [55]:
frame = pd.DataFrame(np.random.standard_normal((4 ,3)) ,
                     columns = list('ABC') ,
                     index = list('abcd'))
frame

          A         B         C
a -1.879443  1.122672 -0.458744
b -0.292460  0.205296 -0.927977
c  0.811708 -0.307763 -0.210041
d  1.723370  0.936006 -0.534231

In [56]:
np.abs(frame)

          A         B         C
a  1.879443  1.122672  0.458744
b  0.292460  0.205296  0.927977
c  0.811708  0.307763  0.210041
d  1.723370  0.936006  0.534231

In [57]:
def f1(x):
  return x.max() - x.min()

In [58]:
f1(frame)

A    3.602813
B    1.430434
C    0.717936
dtype: float64

In [59]:
frame.apply(f1)

A    3.602813
B    1.430434
C    0.717936
dtype: float64

In [60]:
frame

          A         B         C
a -1.879443  1.122672 -0.458744
b -0.292460  0.205296 -0.927977
c  0.811708 -0.307763 -0.210041
d  1.723370  0.936006 -0.534231

In [61]:
frame.apply(f1 , axis = 1)

a    3.002115
b    1.133273
c    1.119471
d    2.257601
dtype: float64

In [62]:
frame.apply(f1 , axis = 'columns')

a    3.002115
b    1.133273
c    1.119471
d    2.257601
dtype: float64

In [63]:
print("The function passed to apply need not return a scalar value , it can also return a Series with multiple values")

The function passed to apply need not return a scalar value , it can also return a Series with multiple values

In [64]:
def f2(x):
  return pd.Series([x.min() , x.max()] , index = ['min' , 'max'])

In [65]:
frame.apply(f2)

            A         B         C
min -1.879443 -0.307763 -0.927977
max  1.723370  1.122672 -0.210041

In [66]:
print("Element wise Python functions can be used with map")

Element wise Python functions can be used with map

In [67]:
def my_format(x):
  return f"{x:2f}"

In [68]:
frame.map(my_format)

           A          B          C
a  -1.879443   1.122672  -0.458744
b  -0.292460   0.205296  -0.927977
c   0.811708  -0.307763  -0.210041
d   1.723370   0.936006  -0.534231

In [69]:
frame['C'].apply(my_format)

a    -0.458744
b    -0.927977
c    -0.210041
d    -0.534231
Name: C, dtype: object

In [70]:
print("DataFrame.map() applies an element wise function across the entire DataFrame while DataFrame.apply() applies a function along an axis")

DataFrame.map() applies an element wise function across the entire DataFrame while DataFrame.apply() applies a function along an axis

### Sorting and Ranking

In [71]:
obj = pd.Series([2 , 1 , 5 , 4 , 3] , index = list('dabec'))
obj

d    2
a    1
b    5
e    4
c    3
dtype: int64

In [72]:
obj.sort_index()

a    1
b    5
c    3
d    2
e    4
dtype: int64

In [73]:
obj.sort_values()

a    1
d    2
c    3
e    4
b    5
dtype: int64

In [74]:
frame = pd.DataFrame(np.arange(24).reshape((4,6)) , index = list("badc") , columns = list("badcfe"))
frame

    b   a   d   c   f   e
b   0   1   2   3   4   5
a   6   7   8   9  10  11
d  12  13  14  15  16  17
c  18  19  20  21  22  23

In [75]:
frame.sort_index()

    b   a   d   c   f   e
a   6   7   8   9  10  11
b   0   1   2   3   4   5
c  18  19  20  21  22  23
d  12  13  14  15  16  17

In [76]:
frame.sort_index(axis = 1)

    a   b   c   d   e   f
b   1   0   3   2   5   4
a   7   6   9   8  11  10
d  13  12  15  14  17  16
c  19  18  21  20  23  22

In [77]:
frame.sort_index(axis = 1 , ascending = False)

    f   e   d   c   b   a
b   4   5   2   3   0   1
a  10  11   8   9   6   7
d  16  17  14  15  12  13
c  22  23  20  21  18  19

In [78]:
obj = pd.Series(np.random.randint(1,10 , size = 5))

In [79]:
obj

0    9
1    1
2    6
3    6
4    5
dtype: int64

In [80]:
obj.sort_index()

0    9
1    1
2    6
3    6
4    5
dtype: int64

In [81]:
obj = pd.Series([1 , 3 , 1 , 5 , 2 , np.nan , -1 , np.nan])
obj

0    1.0
1    3.0
2    1.0
3    5.0
4    2.0
5    NaN
6   -1.0
7    NaN
dtype: float64

In [82]:
obj.sort_values()

6   -1.0
0    1.0
2    1.0
4    2.0
1    3.0
3    5.0
5    NaN
7    NaN
dtype: float64

In [83]:
print("By default the NaN values end up in the end")

By default the NaN values end up in the end

In [84]:
obj.sort_values(na_position = 'first')

5    NaN
7    NaN
6   -1.0
0    1.0
2    1.0
4    2.0
1    3.0
3    5.0
dtype: float64

In [85]:
frame = pd.DataFrame({
    'b':[4 , 7 , -2 , 1] ,
    'c':[0 , 1 , 0 , 1]
})
frame

   b  c
0  4  0
1  7  1
2 -2  0
3  1  1

In [86]:
frame.sort_values('b')

   b  c
2 -2  0
3  1  1
0  4  0
1  7  1

In [87]:
frame.sort_values(['c'])

   b  c
0  4  0
2 -2  0
1  7  1
3  1  1

In [88]:
frame.sort_values(['c' , 'b'])

   b  c
2 -2  0
0  4  0
3  1  1
1  7  1

In [89]:
print("To Sort by multiple values pass a list of names")

To Sort by multiple values pass a list of names

In [90]:
obj = pd.Series([7 , 0 , -1 , 7 , 2 , 3 , 2])
obj

0    7
1    0
2   -1
3    7
4    2
5    3
6    2
dtype: int64

In [91]:
obj.rank()

0    6.5
1    2.0
2    1.0
3    6.5
4    3.5
5    5.0
6    3.5
dtype: float64

In [92]:
obj.rank(method = 'first')

0    6.0
1    2.0
2    1.0
3    7.0
4    3.0
5    5.0
6    4.0
dtype: float64

In [93]:
obj

0    7
1    0
2   -1
3    7
4    2
5    3
6    2
dtype: int64

In [94]:
obj.rank(ascending = False , method = 'first')

0    1.0
1    6.0
2    7.0
3    2.0
4    4.0
5    3.0
6    5.0
dtype: float64

In [95]:
obj.rank(method = 'average')

0    6.5
1    2.0
2    1.0
3    6.5
4    3.5
5    5.0
6    3.5
dtype: float64

In [96]:
obj.rank() == obj.rank(method = 'average')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

In [97]:
frame = pd.DataFrame({
    "b" : [4.3 , 7 , -3 , 2] ,
    "a" : [0 , 1 , 0 , 1] ,
    "c" : [-2 , 5 , 8 , -2.5]
})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [98]:
frame.rank(axis = 0)

     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [99]:
frame.rank(axis = 1)

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [100]:
obj = pd.Series(np.arange(5) , index = list('aabcd'))

In [101]:
obj

a    0
a    1
b    2
c    3
d    4
dtype: int64

In [102]:
obj.index.is_unique

False

In [103]:
obj['a']

a    0
a    1
dtype: int64

In [104]:
obj['c']

np.int64(3)

In [105]:
df = pd.DataFrame(np.random.randint(1 , 100 , (5 , 5)) , index = list('aabbc') , columns = list('AABBC'))
df

    A   A   B   B   C
a   6  95  75   3  66
a  31  48  41  72  70
b  35  25  84   9   8
b  28  96  26  52  62
c  71  29  47  94  26

In [106]:
df.loc[ : ,  'A']

    A   A
a   6  95
a  31  48
b  35  25
b  28  96
c  71  29

In [107]:
df.loc['a']

    A   A   B   B   C
a   6  95  75   3  66
a  31  48  41  72  70

In [108]:
df.loc['c']

A    71
A    29
B    47
B    94
C    26
Name: c, dtype: int64

### Summarizing and Computing Descriptive Statistics

In [109]:
df = pd.DataFrame([[1.3 , np.nan] , [7.1 , -4.5] , [np.nan , np.nan] , [0.75 , -1.3]] , index = list('abcd') , columns = ['one' , 'two'])
df

    one  two
a  1.30  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [110]:
df.sum()

one    9.15
two   -5.80
dtype: float64

In [111]:
df.sum(axis = 1)

a    1.30
b    2.60
c    0.00
d   -0.55
dtype: float64

In [112]:
df.sum(axis = 'columns' , skipna = False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [113]:
df.sum(axis = 'rows' , skipna = False)

one   NaN
two   NaN
dtype: float64

In [114]:
df.mean(axis = 'columns')

a    1.300
b    1.300
c      NaN
d   -0.275
dtype: float64

In [115]:
print("Mean needs atleast one Non nan value to yeild result")

Mean needs atleast one Non nan value to yeild result

In [116]:
df.idxmax()

one    b
two    d
dtype: object

In [117]:
df.idxmin()

one    d
two    b
dtype: object

In [118]:
df.cumsum()

    one  two
a  1.30  NaN
b  8.40 -4.5
c   NaN  NaN
d  9.15 -5.8

In [119]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.050000 -2.900000
std    3.518167  2.262742
min    0.750000 -4.500000
25%    1.025000 -3.700000
50%    1.300000 -2.900000
75%    4.200000 -2.100000
max    7.100000 -1.300000

In [120]:
obj = pd.Series(['a' , 'b' , 'c' , 'd'] * 4)

In [121]:
print(obj)

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
dtype: object

In [122]:
obj.describe()

count     16
unique     4
top        a
freq       4
dtype: object

In [123]:
print('For Non Numeric Values describe gives alternate summary statistics')

For Non Numeric Values describe gives alternate summary statistics

In [124]:
obj = pd.Series([1 , 2 , 3 , 5 , -1 , np.nan , 13 , 13 , 11 , -12 , 234 , 2345 , 1 , 1 , 17 , -9 , 0])

In [125]:
obj.size

17

In [126]:
obj.count()

np.int64(16)

In [127]:
obj.describe()

count      16.000000
mean      164.000000
std       584.491802
min       -12.000000
25%         0.750000
50%         2.500000
75%        13.000000
max      2345.000000
dtype: float64

In [128]:
pd.concat([obj , obj.rank()] , axis = 1)

         0     1
0      1.0   6.0
1      2.0   8.0
2      3.0   9.0
3      5.0  10.0
4     -1.0   3.0
5      NaN   NaN
6     13.0  12.5
7     13.0  12.5
8     11.0  11.0
9    -12.0   1.0
10   234.0  15.0
11  2345.0  16.0
12     1.0   6.0
13     1.0   6.0
14    17.0  14.0
15    -9.0   2.0
16     0.0   4.0

In [129]:
obj.index

RangeIndex(start=0, stop=17, step=1)

In [130]:
obj.loc[17] = 67

In [131]:
obj

0        1.0
1        2.0
2        3.0
3        5.0
4       -1.0
5        NaN
6       13.0
7       13.0
8       11.0
9      -12.0
10     234.0
11    2345.0
12       1.0
13       1.0
14      17.0
15      -9.0
16       0.0
17      67.0
dtype: float64

In [132]:
obj2 = pd.Series([67])
s = pd.concat([obj , obj2])

In [133]:
s

0        1.0
1        2.0
2        3.0
3        5.0
4       -1.0
5        NaN
6       13.0
7       13.0
8       11.0
9      -12.0
10     234.0
11    2345.0
12       1.0
13       1.0
14      17.0
15      -9.0
16       0.0
17      67.0
0       67.0
dtype: float64

In [134]:
print("Concate and loc are two methods to append a new element to the series")

Concate and loc are two methods to append a new element to the series

In [135]:
obj.max()

2345.0

In [136]:
obj.min()

-12.0

In [137]:
obj.idxmax()

11

In [138]:
obj.idxmin()

9

In [139]:
obj.argmin()

np.int64(9)

In [140]:
obj.argmax()

np.int64(11)

In [141]:
obj.sum()

np.float64(2691.0)

In [142]:
obj.mean()

np.float64(158.2941176470588)

In [143]:
obj.apply(lambda x : x+1)

0        2.0
1        3.0
2        4.0
3        6.0
4        0.0
5        NaN
6       14.0
7       14.0
8       12.0
9      -11.0
10     235.0
11    2346.0
12       2.0
13       2.0
14      18.0
15      -8.0
16       1.0
17      68.0
dtype: float64

In [144]:
obj.mean()

np.float64(158.2941176470588)

In [145]:
obj.median()

3.0

In [146]:
print(obj.prod(skipna=False))

nan

In [147]:
prod = 1
for i in obj:
  prod *= i
print(prod)

nan

In [148]:
print(round(obj.prod()))

0

In [149]:
print('By default prod ignores nan Values')

By default prod ignores nan Values

In [150]:
obj.var()

320832.22058823524

In [151]:
import math
ans = 0
for i in obj :
  if pd.notna(i):
    ans += (i - obj.mean())**2
print(ans/(obj.count()-1))

320832.22058823524

In [152]:
np.nan == np.nan

False

In [153]:
np.nan != np.nan

True

In [154]:
print('In python nan is defined as not equal to anything including itself')

In python nan is defined as not equal to anything including itself

In [155]:
obj.skew()

np.float64(4.054964778551968)

In [156]:
obj.kurt()

np.float64(16.57984177730965)

In [157]:
print(list(obj.cummin()))

[1.0, 1.0, 1.0, 1.0, -1.0, nan, -1.0, -1.0, -1.0, -12.0, -12.0, -12.0, -12.0, -12.0, -12.0, -12.0, -12.0, -12.0]

In [158]:
print(list(obj.cummax()))

[1.0, 2.0, 3.0, 5.0, 5.0, nan, 13.0, 13.0, 13.0, 13.0, 234.0, 2345.0, 2345.0, 2345.0, 2345.0, 2345.0, 2345.0, 2345.0]

In [159]:
print(list(obj.cumsum(skipna = False)))

[1.0, 3.0, 6.0, 11.0, 10.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [160]:
print(list(obj.diff()))

[nan, 1.0, 1.0, 2.0, -6.0, nan, nan, 0.0, -2.0, -23.0, 246.0, 2111.0, -2344.0, 0.0, 16.0, -26.0, 9.0, 67.0]

In [161]:
print(list(obj))

[1.0, 2.0, 3.0, 5.0, -1.0, nan, 13.0, 13.0, 11.0, -12.0, 234.0, 2345.0, 1.0, 1.0, 17.0, -9.0, 0.0, 67.0]

In [162]:
print(list(round(obj.pct_change(fill_method=None) , 4)))

[nan, 1.0, 0.5, 0.6667, -1.2, nan, nan, 0.0, -0.1538, -2.0909, -20.5, 9.0214, -0.9996, 0.0, 16.0, -1.5294, -1.0, inf]

### Correlation and Covariance

In [163]:
price = pd.read_pickle('/content/yahoo_price.pkl')
volume = pd.read_pickle('/content/yahoo_volume.pkl')

In [164]:
price.head()

                 AAPL        GOOG         IBM       MSFT
Date
2010-01-04  27.990226  313.062468  113.304536  25.884104
2010-01-05  28.038618  311.683844  111.935822  25.892466
2010-01-06  27.592626  303.826685  111.208683  25.733566
2010-01-07  27.541619  296.753749  110.823732  25.465944
2010-01-08  27.724725  300.709808  111.935822  25.641571

In [165]:
volume.head()

                 AAPL      GOOG      IBM      MSFT
Date
2010-01-04  123432400   3927000  6155300  38409100
2010-01-05  150476200   6031900  6841400  49749600
2010-01-06  138040000   7987100  5605300  58182400
2010-01-07  119282800  12876600  5840600  50559700
2010-01-08  111902700   9483900  4197200  51197400

In [166]:
returns = price.pct_change()

In [167]:
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [168]:
returns['MSFT'].corr(returns['IBM'])

np.float64(0.49976361144151144)

In [169]:
returns['MSFT'].cov(returns['IBM'])

np.float64(8.870655479703546e-05)

In [170]:
returns['MSFT'].cov(returns['IBM']) / (returns['MSFT'].std() * returns['IBM'].std())

np.float64(0.4997636114415115)

In [171]:
returns.corr()

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [172]:
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [173]:
returns.corrwith(returns['IBM'])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [174]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [175]:
print('Passing a DataFrame computes the correlations of matching column names')

Passing a DataFrame computes the correlations of matching column names

In [176]:
returns.corrwith(volume , axis = 1).head()

Date
2010-01-04         NaN
2010-01-05    0.737298
2010-01-06    0.017069
2010-01-07    0.507614
2010-01-08   -0.779646
dtype: float64

### Unique Values , Value Counts and Membership

In [177]:
print("This Section has isin , value_counts , get_indexer , unique")

This Section has isin , value_counts , get_indexer , unique

In [178]:
obj = pd.Series(['c' , 'c' , 'a' , 'a' , 'd' , 'b' , 'b'])

In [179]:
obj

0    c
1    c
2    a
3    a
4    d
5    b
6    b
dtype: object

In [180]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [181]:
obj.value_counts()

c    2
a    2
b    2
d    1
Name: count, dtype: int64

In [182]:
obj

0    c
1    c
2    a
3    a
4    d
5    b
6    b
dtype: object

In [183]:
mask = obj.isin(['b' , 'c'])

In [184]:
mask

0     True
1     True
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [185]:
obj[mask]

0    c
1    c
5    b
6    b
dtype: object

In [186]:
to_match = pd.Series(['c' , 'a' , 'b' , 'b' , 'c' , 'a' , 'e' , 'f'])
unique_vals = pd.Series(['a' , 'b' , 'c'])
indices = pd.Index(unique_vals).get_indexer(to_match)

In [187]:
indices

array([ 2,  0,  1,  1,  2,  0, -1, -1])

In [188]:
print("Compute histogram on multiple related columns in a DataFrame")

Compute histogram on multiple related columns in a DataFrame

In [189]:
data = pd.DataFrame({
    'a' : [1 , 3 , 4 , 3 , 4] ,
    'b' : [2 , 3 , 1 , 2 , 3] ,
    'c' : [1 , 5 , 2 , 4 , 4]
})
data

   a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  2  4
4  4  3  4

In [190]:
data['a'].value_counts()

a
3    2
4    2
1    1
Name: count, dtype: int64

In [191]:
result = data.apply(pd.value_counts).fillna(0)

/tmp/ipykernel_4189/2451317050.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)

In [192]:
result

     a    b    c
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [193]:
result = data.apply(pd.value_counts , axis = 1).fillna(0)

/tmp/ipykernel_4189/1398491101.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts , axis = 1).fillna(0)

In [194]:
result

     1    2    3    4    5
0  2.0  1.0  0.0  0.0  0.0
1  0.0  0.0  2.0  0.0  1.0
2  1.0  1.0  0.0  1.0  0.0
3  0.0  1.0  1.0  1.0  0.0
4  0.0  0.0  1.0  2.0  0.0

In [195]:
data.value_counts()

a  b  c
1  2  1    1
3  2  4    1
   3  5    1
4  1  2    1
   3  4    1
Name: count, dtype: int64

In [196]:
print("In the case of DataFrame.value_counts the result has an index representing the dictinct row as heirarchical index")

In the case of DataFrame.value_counts the result has an index representing the dictinct row as heirarchical index